language: go
go:
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
install:
  - go get -t ./...
script:
  - shopt -s extglob
  - |
    if [[ $(go version) == *1.14* ]]; then
      go test -v -covermode=count -coverprofile=coverage.out .
      go get github.com/mattn/goveralls
      $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    else
      go test -v .
    fi
notifications:
  email:
    applejava@qq.com
